Write-Host "Legacy recovery suite is isolated from default platform gate."
Write-Host "Recovery targets:"
Write-Host "  - tests_legacy/world_streaming.rs"
Write-Host "  - tests_legacy/physics_body_combat/"
Write-Host "  - tests_legacy/content_pipeline.rs"
Write-Host "  - tests_legacy/persistence_full.rs"
Write-Host "  - tests_legacy/runtime_systems/"
Write-Host "  - tests_legacy/gameplay_and_ai.rs"
Write-Host ""
Write-Host "Run recovery manually after API drift repair."